@startuml
scale 100 as 100 pixels

Title Rate Limit - **EARLY**
concise "clock" as C
concise "elapsed" as E
concise "scheduled" as S
concise "allocated" as A

C is the_past #red
E is elapsed  #lightblue
S is scheduled #orange
A is allocated #yellow

@C
732 is future #white
E->C

@E
500 is unseen #white
@500 <-> @732: **error** = 232
A -> C

@S
0 is idle #grey
100 is scheduled #orange
600 is unscheduled #white
@500 <-> @600: **scheduling_delay** =\nelapsed - scheduled = -100

@A
300 is unallocated #white
@300 <-> @500: **wait_time** =\nelapsed - allocated = 200

concise "Ops" as O
@O
0 is op
+100 is op
+100 is op
+100 is op
+100 is op
+100 is op
+100 is op
+100 is op
+100 is op
@enduml
