{
 "title": "Analysis",
 "tags": [ "dse" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "by", "label": "Group By", "query": "cluster,dc,rack,instance" },
   { "name": "rate", "label": "Rate", "query": "1m,5m,10m,30m,1h,6h,12h" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(collectd_cpu_total, cluster)"
   },
   {
    "name": "dc",
    "label": "DataCenter",
    "query": "label_values(collectd_cpu_total{cluster=~\"$cluster\"}, dc)"
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": "label_values(collectd_cpu_total{cluster=~\"$cluster\", dc=~\"$dc\"}, rack)"
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": "label_values(dse_table_read_latency{cluster=~\"$cluster\"}, keyspace)"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "label_values(dse_table_read_latency{keyspace=~\"$keyspace\"}, table)"
   }
  ]
 },
 "panels": [
  { "title": "nosqlbench and DSE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ops and Successful Ops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_m1_rate\"}",
     "legendFormat": "main ops"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_m1_rate\"}",
     "legendFormat": "main success"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_m1_rate\"}",
     "legendFormat": "rampup ops"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_m1_rate\"}",
     "legendFormat": "rampup success"
    }
   ]
  },
  {
   "title": "Error Counts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_errorcounts_WriteTimeoutException_count\"}",
     "legendFormat": "main write timeout"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_errorcounts_ReadTimeoutException_count\"}",
     "legendFormat": "main read timeout"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_errorcounts_OperationTimedOutException_count\"}",
     "legendFormat": "main op timeout"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_errorcounts_WriteTimeoutException_count\"}",
     "legendFormat": "rampup write timeout"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_errorcounts_ReadTimeoutException_count\"}",
     "legendFormat": "rampup read timeout"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_errorcounts_OperationTimedOutException_count\"}",
     "legendFormat": "rampup op timeout"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_errorcounts_NoHostAvailableException_count\"}"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_errorcounts_UnavailableException_count\"}"
    }
   ]
  },
  {
   "title": "service time distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_min\"}",
     "legendFormat": "main min"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_p50\"}",
     "legendFormat": "main p50"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_p75\"}",
     "legendFormat": "main p75"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_p95\"}",
     "legendFormat": "main p95"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_p98\"}",
     "legendFormat": "main p98"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_p99\"}",
     "legendFormat": "main p99"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_p999\"}",
     "legendFormat": "main p999"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_min\"}",
     "legendFormat": "rampup min"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_p50\"}",
     "legendFormat": "rampup p50"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_p75\"}",
     "legendFormat": "rampup p75"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_p95\"}",
     "legendFormat": "rampup p95"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_p99\"}",
     "legendFormat": "rampup p99"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_p999\"}",
     "legendFormat": "rampup p999"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_max \"}",
     "legendFormat": "main max"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_max\"}",
     "legendFormat": "rampup max"
    }
   ]
  },
  {
   "title": "service time max",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_max\"}",
     "legendFormat": "main max"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_success_max\"}",
     "legendFormat": "rampup max"
    }
   ]
  },
  {
   "title": "p75 client overhead",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_bind_p75\"}",
     "legendFormat": "main bind p75"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_execute_p75\"}",
     "legendFormat": "main execute p75"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_p75\"}",
     "legendFormat": "main result p75"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_read_input_p75\"}",
     "legendFormat": "main input p75"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_bind_p75\"}",
     "legendFormat": "rampup bind p75"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_execute_p75\"}",
     "legendFormat": "rampup execute p75"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_p75\"}",
     "legendFormat": "rampup result p75"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_read_input_p75\"}",
     "legendFormat": "rampup input p75"
    }
   ]
  },
  {
   "title": "p99 client overhead",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_bind_p99\"}",
     "legendFormat": "main bind p99"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_execute_p99\"}",
     "legendFormat": "main execute p99"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_p99\"}",
     "legendFormat": "main result p99"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_read_input_p99\"}",
     "legendFormat": "main input p99"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_bind_p99\"}",
     "legendFormat": "rampup bind p99"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_execute_p99\"}",
     "legendFormat": "rampup execute p99"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_result_p99\"}",
     "legendFormat": "rampup result p99"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_read_input_p99\"}",
     "legendFormat": "rampup input p99"
    }
   ]
  },
  {
   "title": "op tries distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_tries_min\"}",
     "legendFormat": "main min tries"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_tries_p50  \"}",
     "legendFormat": "main median tries"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_tries_p999\"}",
     "legendFormat": "main p999 tries"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_tries_max\"}",
     "legendFormat": "main max tries"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_tries_min\"}",
     "legendFormat": "rampup min tries"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_tries_p50  \"}",
     "legendFormat": "rampup median tries"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_tries_p999\"}",
     "legendFormat": "rampup p999 tries"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_tries_max\"}",
     "legendFormat": "rampup max tries"
    }
   ]
  },
  {
   "title": "Storage Load / $by",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_load_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "Disk Rate / sec",
   "type": "graph",
   "description": "Read/Write bytes/sec",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "Bps", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(collectd_disk_disk_octets_read_total{disk=~\".*md0\"}[$rate])",
     "legendFormat": "{{instance}} {{disk}} - Reads"
    },
    {
     "expr": "irate(collectd_disk_disk_octets_write_total{disk=~\".*md0\"}[$rate])",
     "legendFormat": "{{instance}} {{disk}} - Write"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bps", "label": "Read (-) /  Write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(collectd_interface_if_octets_rx_total[1m]) * 8",
     "legendFormat": "{{instance}} {{interface}} read "
    },
    {
     "expr": "irate(collectd_interface_if_octets_tx_total[1m]) * 8",
     "legendFormat": "{{instance}} {{interface}} write"
    }
   ]
  },
  {
   "title": "Cycle Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_cycles_responsetime_count\"}",
     "legendFormat": "response count"
    },
    {
     "expr": "{__name__=~\"nosqlbench__workloads_.+_cycles_servicetime_count\"}",
     "legendFormat": "response count"
    }
   ]
  },
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Nodes Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dse_compaction_completed_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"} >= 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(absent(sum(rate(dse_compaction_completed_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[2m])))) OR vector(0)"
    }
   ]
  },
  {
   "title": "Compactions / $rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(dse_compaction_completed_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Requests / $rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_latency_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Dropped Messages / $rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(dse_table_dropped_mutations_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(dse_client_connected_native_clients{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"})"
    }
   ]
  },
  {
   "title": "Client Timeouts / $rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_timeouts_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Total Hints",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(dse_storage_hints_on_disk_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"})"
    }
   ]
  },
  {
   "title": "Live Data Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 20 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dse_table_live_disk_space_used_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"})"
    }
   ]
  },
  {
   "title": "Coordinator Metrics (no keyspace/table filters apply)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Served / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dse_client_request_latency_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by, request_type)",
       "legendFormat": "{{$by}}:{{request_type}}"
      }
     ]
    },
    {
     "title": "Clients Connected / $by",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dse_client_connected_native_clients{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}) by ($by)",
       "legendFormat": "{{$by}}"
      }
     ]
    },
    {
     "title": "Client Timeouts / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dse_client_request_timeouts_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
       "legendFormat": "{{$by}}"
      }
     ]
    },
    {
     "title": "Coordinator Read Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(dse_client_request_latency_bucket{request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dse_client_request_latency_bucket{request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dse_client_request_latency_bucket{request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dse_client_request_latency_bucket{request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dse_client_request_latency_bucket{request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(dse_client_request_latency_bucket{request_type=\"read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Coordinator Write Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(dse_client_request_latency_bucket{request_type=\"write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dse_client_request_latency_bucket{request_type=\"write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dse_client_request_latency_bucket{request_type=\"write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dse_client_request_latency_bucket{request_type=\"write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dse_client_request_latency_bucket{request_type=\"write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(dse_client_request_latency_bucket{request_type=\"write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Coordinator Range Read Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(dse_client_request_latency_bucket{request_type=\"range_slice\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dse_client_request_latency_bucket{request_type=\"range_slice\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dse_client_request_latency_bucket{request_type=\"range_slice\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dse_client_request_latency_bucket{request_type=\"range_slice\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dse_client_request_latency_bucket{request_type=\"range_slice\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(dse_client_request_latency_bucket{request_type=\"range_slice\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Coordinator CAS Read Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(dse_client_request_latency_bucket{request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dse_client_request_latency_bucket{request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dse_client_request_latency_bucket{request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dse_client_request_latency_bucket{request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dse_client_request_latency_bucket{request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(dse_client_request_latency_bucket{request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Coordinator CAS Read Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(dse_client_request_latency_bucket{request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dse_client_request_latency_bucket{request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dse_client_request_latency_bucket{request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dse_client_request_latency_bucket{request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dse_client_request_latency_bucket{request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(dse_client_request_latency_bucket{request_type=\"cas_read\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Coordinator View Write Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(dse_client_request_latency_bucket{request_type=\"view_write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dse_client_request_latency_bucket{request_type=\"view_write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dse_client_request_latency_bucket{request_type=\"view_write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dse_client_request_latency_bucket{request_type=\"view_write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dse_client_request_latency_bucket{request_type=\"view_write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(dse_client_request_latency_bucket{request_type=\"view_write\", cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    }
   ]
  },
  {
   "title": "Table Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Coordinator Table Read Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(dse_table_coordinator_read_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(irate(dse_table_coordinator_read_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(dse_table_coordinator_read_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(dse_table_coordinator_read_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(dse_table_coordinator_read_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(irate(dse_table_coordinator_read_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Local Table Read Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(dse_table_read_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(irate(dse_table_read_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(dse_table_read_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(dse_table_read_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(dse_table_read_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(irate(dse_table_read_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Local Table Write Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(dse_table_write_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(irate(dse_table_write_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(dse_table_write_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(dse_table_write_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(dse_table_write_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(irate(dse_table_write_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Coordinator Table Range Scan Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(dse_table_coordinator_scan_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(irate(dse_table_coordinator_scan_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(dse_table_coordinator_scan_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(dse_table_coordinator_scan_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(dse_table_coordinator_scan_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(irate(dse_table_coordinator_scan_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Local Table Range Scan Latency / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(dse_table_range_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P50 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(irate(dse_table_range_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(dse_table_range_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(dse_table_range_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(dse_table_range_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(irate(dse_table_range_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
       "legendFormat": "$by:{{$by}} P999"
      }
     ]
    },
    {
     "title": "Memtable Space  $keyspace.$table / $by",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(dse_table_memtable_off_heap_size{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
       "legendFormat": "{{$by}} : Off Heap"
      },
      {
       "expr": "sum(dse_table_memtable_on_heap_size{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
       "legendFormat": "{{$by}} : On Heap"
      },
      {
       "expr": "sum(dse_table_memtable_live_data_size{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
       "legendFormat": "{{$by}} : Data Size"
      },
      {
       "expr": "sum(idelta(dse_table_memtable_switch_count_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by ($by)",
       "legendFormat": "{{$by}} : Flushes"
      },
      {
       "expr": "sum(idelta(dse_table_pending_flushes_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by ($by)",
       "legendFormat": "{{$by}} : Pending Flushes"
      }
     ]
    },
    {
     "title": "SSTables Per Read / Node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dse_table_ss_tables_per_read_histogram{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", quantile=~\".\\\\d+\"}) by (quantile, instance) * 1000",
       "legendFormat": "Node {{instance}} P{{quantile}}"
      }
     ]
    },
    {
     "title": "Tombstones Scanned / Node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dse_table_tombstone_scanned_histogram{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", quantile=~\".\\\\d+\"}) by (quantile, instance) * 1000",
       "legendFormat": "{{instance}} : P{{quantile}}"
      }
     ]
    }
   ]
  },
  { "title": "Storage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Live Disk Space Used / $by",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(dse_table_total_disk_space_used_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "Storage Load / $by",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(dse_storage_load_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "Total Hints / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dse_storage_total_hints_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "Hints on Disk / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dse_storage_hints_on_disk_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}}"
    }
   ]
  },
  {
   "title": "CQL Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prepared Statement Ratio / $by",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(dse_cql_prepared_statements_ratio{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
       "legendFormat": "{{$by}}"
      }
     ]
    },
    {
     "title": "Prepared Statements / $by",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(dse_cql_prepared_statements_count{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}) by ($by)",
       "legendFormat": "{{$by}}"
      }
     ]
    },
    {
     "title": "Executed Prepared Statements / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dse_cql_prepared_statements_executed_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by ($by)",
       "legendFormat": "{{$by}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM G1 Eden Space Used / node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dse_jvm_memory_pool_used{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", dse=\"jvm.memory.pools.g1_eden_space.used\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "JVM G1 Old Gen Used / node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dse_jvm_memory_pool_used{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", dse=\"jvm.memory.pools.g1_old_gen.used\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "JVM G1 Survivor Space / node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dse_jvm_memory_pool_used{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", dse=\"jvm.memory.pools.g1_survivor_space.used\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "JVM GC Young Gen / node / $rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "increase(dse_jvm_gc_time{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", dse=\"jvm.gc.g1_young_generation.time\"}[$rate])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "JVM GC Old Gen Count / node / $rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(dse_jvm_gc_count{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", dse=\"jvm.gc.g1_young_generation.count\"}[$rate])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "JVM GC Old Gen / node / $rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "increase(dse_jvm_gc_time{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", dse=\"jvm.gc.g1_old_generation.time\"}[$rate])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "JVM GC Old Gen Count / node / $rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(dse_jvm_gc_count{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", dse=\"jvm.gc.g1_old_generation.count\"}[$rate])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  { "title": "Compaction Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Pending Compactions / node / $rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(dse_compaction_pending_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}) by ($by)",
     "legendFormat": "{{ $by }}"
    }
   ]
  },
  {
   "title": "Completed Compactions / node / $rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dse_compaction_completed_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
     "legendFormat": "{{ $by }}"
    }
   ]
  },
  {
   "title": "Compacted Bytes / node / $rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dse_compaction_bytes_compacted_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
     "legendFormat": "{{ $by }}"
    }
   ]
  },
  { "title": "Hint Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Hint Delays / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dse_hints_hint_delays_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
     "legendFormat": "{{ $by }}"
    }
   ]
  },
  {
   "title": "Hints Succeeded / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dse_hints_hints_succeeded_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
     "legendFormat": "{{ $by }}"
    }
   ]
  },
  {
   "title": "Hints Failed / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dse_hints_hints_failed_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
     "legendFormat": "{{ $by }}"
    }
   ]
  },
  { "title": "NodeSync Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Repair Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repairs Completed / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dse_table_repair_jobs_completed_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (table, $by)",
       "legendFormat": "{{ $by }} : {{ table }}"
      }
     ]
    },
    {
     "title": "Read Repair Requests / $by / $rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dse_table_read_repair_requests_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (table, $by)",
       "legendFormat": "{{ $by }} : {{ table }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Streaming Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Streaming Incoming Bytes / $by / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(dse_streaming_incoming_bytes_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    },
    {
     "title": "Streaming Outgoing Bytes / $by / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(dse_streaming_outgoing_bytes_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}[$rate])) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chunk Cache Hit Rate / $by",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(dse_cache_hit_rate{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", cache_name=\"chunk_cache\"}) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    },
    {
     "title": "Counter Cache Hit Rate / $by",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(dse_cache_hit_rate{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", cache_name=\"counter_cache\"}) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    },
    {
     "title": "Key Cache Hit Rate / $by",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(dse_cache_hit_rate{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", cache_name=\"key_cache\"}) by ($by)",
       "legendFormat": "{{ $by }}"
      }
     ]
    }
   ]
  },
  {
   "title": "TPC Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPC Task Types",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dse_thread_pools_completed_tasks{pool_name=~\"tpc_.*\"}[$rate])) by (pool_name, $by)",
       "legendFormat": "{{pool_name}}"
      }
     ]
    }
   ]
  }
 ]
}