{
 "title": "NoSQLBench",
 "tags": [ "dse" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "NoSQLBench Metrics Guide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "content": "The descriptions below are in the same position as the metric they desscribe.\nYou can collapse this row when you no longer need the descriptions.\nSome of the descriptions have additional details if you scroll with\nyour mouse wheel.\n\n\n"
  },
  {
   "title": "Ops and Successful Ops",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "content": "These two metrics show the 1-minute averaged ops per second for all ops (successes and errors) and succesful ops (no errors during execution) separately.\n\nWhen there are no errors, these metrics should be the same. When there are errors, there will be a difference. In that case, you can look at the error metrics to learn more about what is happening.\n\nBy comparing these two metrics for any activity, you have a quick first-glance sanity check that your tests are configured properly and\nthat there are no serious configuration or resource issues. In addition, this is the primary throughput metric.\n\n\n\n\n\n"
  },
  {
   "title": "Error Counts",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "content": "When an exception is caught and counted in a scenario, a specially named metric is emited which includes a simplified name of the error type.\nEach of these metrics is created as needed in the NoSQLBench runtime.\n\nThese metrics are formated with a name pattern of `errorcounts.NAME` where NAME is the simple name\nof the exception class which was caught during the operation. For example, For an activity\nnamed foo (with alias=foo), you would expect an exception named 'FooTimeoutException' to be shown\nwith a metric name of ...`foo.errorcounts.FooTimeoutException`\n\n\n\n\n"
  },
  {
   "title": "Service Time Distribution",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "content": "The service time distribution is an HDR histogram that represents the time elapsed from when an operation is submitted for execution to when its result has been received.\n\nFrom the vantage point of the NoSQLBench runtime, this is a client-side metric. Thus, the service time captures the processing time that an application would see, including driver logic, wire time (transport), and server-side processing. \n\nThis metric does not include the waittime or the responsetime metrics. These metrics are only meaningful (and provided) when a `cyclerate=` is provided to an activity. When computing the responsetime metric, the servicetime is added to the waittime for a given operation.\n"
  },
  {
   "title": "Op Tries Distribution",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "content": "The tries distribution is an HDR histogram which represents how many times an operation was submitted. In a well balanced system,\ntries should be 1 across the board.\n\nEvery operation which is executed within NoSQLBench should have a `tries` metric. For example, with CQL, the number of times an operation is submitted\nbefore it is succesful is ideally 1. If you are overloading your target system, thus forcing resource contention, you may see operations timeout.\n\nBy default, NoSQLBench will try up to 10 times to submit operations before giving up and throwing an error for an operation.\n\nThe tries metric can be used as a low-noise indicator of system saturation. For example, if you are running a system marginally\nbeyond its capacity, the tries for operations will go above 1 at the higher percentiles such as P99. If you increase the load even further, more retries\nwill be needed and less work will be completed, thus showing higher retries at even lower percentiles, like P95, for example.\n\nAs such, you can use the tries metric as an indicator of relative saturation."
  },
  {
   "title": "P75 NB Internals",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "content": "This panel shows the P75 service times for the internal stages of NoSQLBench processing. It provides a sanity check to ensure that the client processing time is low and predictable. \n\nIf there are spikes in this data, then you are likely trying to run your workloads on insufficient client hardware. In order to ensure high fidelity results in the other metrics, the client\nneeds to be capable of driving the workload without saturating or introducing signifcant local resource contention.\n\n- **read-input** - the time it takes for a worker thread to acquire a stride (range of cycles) for execution.\n- **bind** - the time it takes to convert a cycle value into a set of fields for us in an operation.\n- **execute** - the time it takes to submit work to a protocol-specific driver."
  },
  {
   "title": "P99 NB Internals",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "content": "This panel shows the P99 service times for the internal stages of NoSQLBench processing. It provides a sanity check to ensure that the client processing time is low and predictable. \n\nIf there are spikes in this data, then you are likely trying to run your workloads on insufficient client hardware. In order to ensure high fidelity results in the other metrics, the client\nneeds to be capable of driving the workload without saturating or introducing signifcant local resource contention.\n\n- **read-input** - the time it takes for a worker thread to acquire a stride (range of cycles) for execution.\n- **bind** - the time it takes to convert a cycle value into a set of fields for us in an operation.\n- **execute** - the time it takes to submit work to a protocol-specific driver."
  },
  {
   "title": "Service Time Range",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "content": "This panel simply breaks out the service time range in a simpler view. This is a good metric to look at when you want to know what the best and worse case value is for any given histogram interval.\n\nThese values come from a discrete HDR histogram reservoir. They are the actual best and worst service times, unaffected by time-decaying reservoir logic.\n"
  },
  {
   "title": "Cycle Count",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "content": "This is a simple visual reference for the cycle count within each activity. This makes it easy to see the relative progress of an activity over time."
  },
  { "title": "NoSQLBench Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Ops and Successful Ops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "result{type=\"avg_rate\",avg_of=\"1m\"}",
     "legendFormat": "{{alias}}-allops"
    },
    {
     "expr": "result_success{type=\"avg_rate\",avg_of=\"1m\"}",
     "legendFormat": "{{alias}}-okops"
    }
   ]
  },
  {
   "title": "Error Counts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"errorcounts.*\"}",
     "legendFormat": "{{alias}}-{{error}}"
    }
   ]
  },
  {
   "title": "service time distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "result_success{type=\"pctile\"}",
     "legendFormat": "{{alias}}-p{{pctile}}"
    }
   ]
  },
  {
   "title": "op tries distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tries{type=\"pctile\"}",
     "legendFormat": "{{alias}}-p{{pctile}}"
    }
   ]
  },
  {
   "title": "p75 client overhead",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"read_input|bind|execute\",type=\"pctile\",pctile=\"75\"}",
     "legendFormat": "{{alias}}-{{__name__}}-p{{pctile}}"
    }
   ]
  },
  {
   "title": "p99 client overhead",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"read_input|bind|execute\",type=\"pctile\",pctile=\"99\"}",
     "legendFormat": "{{alias}}-{{__name__}}-p{{pctile}}"
    }
   ]
  },
  {
   "title": "service time range",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "result_success{type=\"pctile\",pctile=\"0\"}",
     "legendFormat": "{{alias}}-min"
    },
    {
     "expr": "result_success{type=\"pctile\",pctile=\"100\"}",
     "legendFormat": "{{alias}}-max"
    }
   ]
  },
  {
   "title": "Cycle Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cycles_servicetime{type=\"counter\"}",
     "legendFormat": "{{alias}}-count"
    }
   ]
  }
 ]
}