@startuml
Participant user as u
Participant client as c
Participant resource as cr
Participant transport as t
Participant server as s

group responsetime
 u -> c: request
 activate c #Black
 group waittime
  c -> cr: wait
  activate cr #Yellow
  note left of cr: client\nwaits\nfor\nresource
  cr -> c:
  deactivate cr
 end

 group servicetime
 c ->> t: request
 activate t #Red
  group servertime
   t ->> s: request
   deactivate t
   activate s #Blue
   note right of s: server\nprocesses\nrequest
   s ->> t: response
   deactivate s
   activate t #Red
  end
  t ->> c: response
  deactivate t
 end
 c -> u: response
 deactivate c
end

@enduml