#!/bin/bash
cd mvn-defaults
#set -x
CURRENT_VERSION=$(mvn help:evaluate -Dexpression=revision -q -DforceStdout)
RELEASE_VERSION=${CURRENT_VERSION%%-SNAPSHOT}
RELEASE_TAG="${RELEASE_VERSION}-release"
printf "release tag: '%s'\n" "${RELEASE_TAG}"

if [ "$1" == "-f" ]
then
 git tag -f "${RELEASE_TAG}"
else
 git tag "${RELEASE_TAG}"
fi

