#!/bin/bash
cd mvn-defaults
#set -x
CURRENT_VERSION=$(mvn help:evaluate -Dexpression=revision -q -DforceStdout)
RELEASE_VERSION=${CURRENT_VERSION%%-SNAPSHOT}
RELEASE_TAG="${RELEASE_VERSION}-release"
printf "release tag: '%s'\n" "${RELEASE_TAG}"
set -e

if [ "$1" == "-f" ]
then
 git tag -f "${RELEASE_TAG}" \
 && git push -f origin "${RELEASE_TAG}" \
 && printf "force pushed tag %s to origin, triggering build.\n" "${RELEASE_TAG}"
else
 git tag "${RELEASE_TAG}" \
 && git push origin "${RELEASE_TAG}" \
 && printf "pushed tag %s to origin, triggering build.\n" "${RELEASE_TAG}"
fi


