#!/usr/bin/env bash

CURL="$(command -v curl)"
if [ -z "$CURL" ]; then
 printf "attempting to install curl\n";
 sudo apt install curl
fi

if [ -d "local/node" ]
then
 printf "The nodejs directory was already populated. If you need to re-install, un-install it first.\n"
 exit 0
fi

mkdir -p local
pushd local || exit
curl -O https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.xz
tar xf node-v12.16.1-linux-x64.tar.xz
rm node*.xz
mv node-v12.16.1-linux-x64 node12
echo 'export PATH=local/node12/bin:$PATH' > env.sh



